import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';

// @ts-expect-error - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
import * as build from '../build/server/index.js';
import { getLoadContext } from '../load-context';

export const onRequest = createPagesFunctionHandler({
  build,
  getLoadContext,
});
